//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGateway.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User Id=software_shahab;Password=Shahab123;Data Source=(DESCRIPTION =    (ADDRESS" +
            " = (PROTOCOL = TCP)(HOST = 192.168.50.62)(PORT = 1525))    (CONNECT_DATA =      " +
            "(SERVER = DEDICATED)      (SERVICE_NAME = DBTEST12.enb.local)    )  )")]
        public string oradb {
            get {
                return ((string)(this["oradb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<RSAKeyValue><Modulus>0k3lCzFiZwg/njyoMR0Jkcs6xRfSR7p766VWAm266V24lYPBxZgLxuuxQNF" +
            "Aj+ReSMJ5joUIT24PKQLSVmzvoXUTLv6FpM3F5CAN8xhljMPFA+T70e8aNUzKGmxQeGFmDIXw/D6d6Rz" +
            "+3ryTe/GAP3hA1T6BtEt96IVLhlK1DLsWhlO3wv7Zj9DlYUH4vpwn81eA0dwsTamUmAl8c4RaXuUHsyH" +
            "UfnZVYpK3l3T1ch5BGpxsvL15gNGBHYM+Xl8Z0dcCH1oVDYLa9GNdBQ3KjI00TiDYhWtngUGeXHwcIPR" +
            "T3/ETn8JuX+ZKHI2Tp9h0oq9z74cN9UK2RwSn+upf1Q==</Modulus><Exponent>AQAB</Exponent>" +
            "<P>607h8RAjzTzq45mtJo+to1wge1V43/DsA3/4yvBpQCXh4wvixAdtKKH5hCRivraS2EZiQRUkQUjdE" +
            "5PS1KiOaAmBECamzkGCC4u1SFyRBsxi0AOlsAEWJ/ewrciLXMJXcLNdkSqgug8tdZnkM9nF42oMBCMK6" +
            "RdKCUDq3P1yuA8=</P><Q>5Mwj2k9BORZI84LZWpkLCN7pQcE+0ofQwnGhVUjlANIzwO6tLXCLfyMa/y" +
            "TpqwIRQRf19gXexNCNekRCg6SNB2aFqk1CKx8409wgINoHGksdoYURajYWH0jd3Fsns7MN3IF3FoQRZ9" +
            "4vdOjnon44bQQZIg1WGYP3teXvg3VHZds=</Q><DP>10fRMRJaHvCn2dmEb+4tp3KnCQ+WyhOKal1Piq" +
            "PPN3AxLN939W7x8KXYOYxshx1UVeh3BiJIjC4UjU/GKOeZeheP6+3g2H1YdCW6klyWFskxciyUDuW/lo" +
            "tnKmd7ET+Abky7ww9kAzXVmm1UOhf4k2o3WiWRWtYC11p8RfjfVwM=</DP><DQ>F4e3GDiWaJyWHBUU7" +
            "XBX5i2mp5CMOXKmUZkGEpNQmekEUY86WDX+4rBlkl/leCTaSWuBbC/mXS9lnXFvtcIyjtRIYt9XMsAfR" +
            "Aqbc0V4/YdEINxikh3F4KnJx2PIjX6YqljWOoaSk7ASCV/6koeQngWR4CKm/DDKRPbEzyw8j4k=</DQ>" +
            "<InverseQ>Kf81+54Q0obv4rGQwJhoEWkfCHVHTGewylMgX6qUitP4+R4JAqX+jWn4eI9JYqc2UQ9A8e" +
            "m/wEHjkOlrY36EWGGpopQfWkw2tM/E5MtGsWZOCU0SHH8yP13tYn8tVAwfds0ngyWWkm+DEn+bZz4zQG" +
            "90mpP6pz7OoO4cfdS01oQ=</InverseQ><D>igudnJJHIJC2id0RHmQMIwp/Ql7XpkPQEieOZLu4pHTj" +
            "tCkvqc+bc3DFAmIY+hsSlLorZpUGlnUNOINkpFyPk7Ew7XkfKsXz70HnRjoudo8PJPZLIkvMLU6Bn4SX" +
            "8d0lSnUlcb58k0d4OacZPJOS9pauIAwOwdWICXht0fc6Zua7RbZ5xAt2MGR7uDxCTD5tuNY68/4GhvEG" +
            "2RNiO8fFNspNkBsbJeibbTUpimBtD0wTBy7S8Z1dIXPfniR8j7qV/ezlDrGJVApVobaQYmaz3GSK+WDn" +
            "DZ+8QRwL2xaFNZEF9I4MgMmNFOX9vgUBiogLmf1q+V00uFjH3vJB0DC1JQ==</D></RSAKeyValue>\n")]
        public string PrivateKey {
            get {
                return ((string)(this["PrivateKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@p!G@teW@y")]
        public string LoginPass {
            get {
                return ((string)(this["LoginPass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pichak.nibn.ir:9911/api/pichak/")]
        public string commonUrl {
            get {
                return ((string)(this["commonUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<RSAKeyValue><Modulus>0k3lCzFiZwg/njyoMR0Jkcs6xRfSR7p766VWAm266V24lYPBxZgLxuuxQNFAj+ReSMJ5joUIT24PKQLSVmzvoXUTLv6FpM3F5CAN8xhljMPFA+T70e8aNUzKGmxQeGFmDIXw/D6d6Rz+3ryTe/GAP3hA1T6BtEt96IVLhlK1DLsWhlO3wv7Zj9DlYUH4vpwn81eA0dwsTamUmAl8c4RaXuUHsyHUfnZVYpK3l3T1ch5BGpxsvL15gNGBHYM+Xl8Z0dcCH1oVDYLa9GNdBQ3KjI00TiDYhWtngUGeXHwcIPRT3/ETn8JuX+ZKHI2Tp9h0oq9z74cN9UK2RwSn+upf1Q==</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>
")]
        public string PublicKey {
            get {
                return ((string)(this["PublicKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d2b202615d70ef521a81e939c6219830bf00f4aa")]
        public string certificateThumbPrint {
            get {
                return ((string)(this["certificateThumbPrint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BEGNIRTHXXX")]
        public string UserNameAuthen {
            get {
                return ((string)(this["UserNameAuthen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A3#ujT4_m:;.")]
        public string PasswordAuthen {
            get {
                return ((string)(this["PasswordAuthen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Operation\\Net")]
        public string PathCertFolder {
            get {
                return ((string)(this["PathCertFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CertificatePichakNet")]
        public string PathCertFile {
            get {
                return ((string)(this["PathCertFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pi@p@ssw0rd")]
        public string PathCertPass {
            get {
                return ((string)(this["PathCertPass"]));
            }
        }
    }
}
