//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGateway.SendSmsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:send_sms_web_service", ConfigurationName="SendSmsService.send_sms_web_servicePortType")]
    public interface send_sms_web_servicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:send_sms_web_service#send_sms_web_service", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string send_sms_web_service(string username, string password, string source, string destination, string message_body, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:send_sms_web_service#send_sms_web_service", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> send_sms_web_serviceAsync(string username, string password, string source, string destination, string message_body, string language);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface send_sms_web_servicePortTypeChannel : APIGateway.SendSmsService.send_sms_web_servicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class send_sms_web_servicePortTypeClient : System.ServiceModel.ClientBase<APIGateway.SendSmsService.send_sms_web_servicePortType>, APIGateway.SendSmsService.send_sms_web_servicePortType {
        
        public send_sms_web_servicePortTypeClient() {
        }
        
        public send_sms_web_servicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public send_sms_web_servicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public send_sms_web_servicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public send_sms_web_servicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string send_sms_web_service(string username, string password, string source, string destination, string message_body, string language) {
            return base.Channel.send_sms_web_service(username, password, source, destination, message_body, language);
        }
        
        public System.Threading.Tasks.Task<string> send_sms_web_serviceAsync(string username, string password, string source, string destination, string message_body, string language) {
            return base.Channel.send_sms_web_serviceAsync(username, password, source, destination, message_body, language);
        }
    }
}
